name: Java Github Action with Gradle 111

on: [pull_request,workflow_dispatch]
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  #workflow_dispatch:
  #  inputs: [ "main" ]
env:
  USER_ID: $ {{ secrets.TID }}
  USER_PWD: $ {{ secrets.TPWD }}
  TEST1: ${{ secrets.TID }}
  TEST2: ${{ secrets.SMKWON_SSH_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: |
         echo "Log level: $LEVEL"
         echo "Tags: $TAGS"
         echo "Environment: $ENVIRONMENT"
      env:
         LEVEL: ${{ inputs.logLevel }}
         TAGS: ${{ inputs.tags }}
         ENVIRONMENT: ${{ inputs.environment }}

