name: Java Github Action with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
env:
  USER_ID: $ {{ secrets.TID }}
  USER_PWD: $ {{ secrets.TPWD }}
  TEST1: ${{ secrets.TID }}
  TEST2: ${{ secrets.SMKWON_SSH_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: |
         echo "Log level: $LEVEL"
         echo "Tags: $TAGS"
         echo "Environment: $ENVIRONMENT"
      env:
         LEVEL: ${{ inputs.logLevel }}
         TAGS: ${{ inputs.tags }}
         ENVIRONMENT: ${{ inputs.environment }}
    - uses: actions/checkout@v3
    - run: echo $TEST1
    - run: echo $TEST2
    - run: echo $USER_ID
    - name: SHOW USER_ID
      run: echo $USER_ID
    - name: SHOW USER_PWD
      run: echo $USER_PWD
    - name: Run pwd
      run: pwd
    - name: Run ls -al
      run: ls -al
    - name: chmod +x gradlew
      run: chmod +x gradlew
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Run pwd
      run: pwd
    - name: Run ls -al2
      run: ls -al
    - name: Run ls -al3
      run: ls -al build/libs
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: "54.72.146.174"
        username: "fmmsysops.fmm-dev"
        password: "devSposysmmf>%2"
        port: 4222
        source: "build/libs/smkown-0.0.1-SNAPSHOT.jar"
        target: "test"
